# Generated by Django 5.1.1 on 2024-11-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Temperatura', max_length=50)),
                ('unidade_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('localizacao', models.CharField(max_length=255)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('status_operacional', models.BooleanField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LuminosidadeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Temperatura', max_length=50)),
                ('unidade_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('localizacao', models.CharField(max_length=255)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('status_operacional', models.BooleanField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Temperatura', 'Temperatura'), ('Umidade', 'Umidade'), ('Contador', 'Contador'), ('Luminosidade', 'Luminosidade')], max_length=50)),
                ('mac_address', models.CharField(max_length=20, null=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('localizacao', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('unidade_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('status_operacional', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Temperatura', max_length=50)),
                ('unidade_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('localizacao', models.CharField(max_length=255)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('status_operacional', models.BooleanField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UmidadeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Temperatura', max_length=50)),
                ('unidade_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('localizacao', models.CharField(max_length=255)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('status_operacional', models.BooleanField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
